app:
    resource: "@BlogBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /
