blog_comments:
    resource: "@BlogBundle/Resources/config/routing/comments.yml"
    prefix:   /comments

blog_article:
    resource: "@BlogBundle/Resources/config/routing/article.yml"
    prefix:   /article

blog_category:
    resource: "@BlogBundle/Resources/config/routing/category.yml"
    prefix:   /category

blog_parameters:
    resource: "@BlogBundle/Resources/config/routing/blog.yml"
    prefix:   /blog

admin:
    path:     /admin
    defaults: { _controller: "BlogBundle:Default:admin" }

profil:
    path:     /profil

profil_show:
    path:     /profil/{id}
    defaults: { _controller: "UserBundle:Profil:index" }